import React from 'react'
import Image from '../public/images/house1_croped.jpeg'

const Residential = () => {
  return (
    <div className='residentialContainer'>
      <div className='mainImage'>
        <img src={Image} alt=""/>
        <h1>We make solar simple</h1>
      </div>
      <div className='mainContent'>
        <div className='services'>
          <h1>Our Service</h1>
          <p>Solar offers that remove the hassle from solar power.
            Freedom Energy deliver the industries best solar products combined with outstanding customer service and
            installation designed to take the guess work out of switching to solar.
            We take care of everything required to get you started, from site feasibility,
            network applications and installation of your system.
            We also have the best industry warranties that cover you for the life of your system.</p>
        </div>
        <div className='whySolar'>
          <h1>Why Go Solar</h1>
          <div className='item'>
            <h3>Save on electricity bills</h3>
            <p>Installing solar panels significantly reduces monthly electricity bills and dependence on the power grid</p>
          </div>
          <div className='item'>
            <h3>Increase property value</h3>
            <p>Studies have shown properties sell up to 20 percent faster and at a 17 percent premium compared to homes without solar</p>
          </div>
          <div className='item'>
            <h3>Reduce your carbon footprint</h3>
            <p>Unlike energy generated by fossil fules, solar doesn't release harmful carbon dioxide (CO2)</p>
          </div>
          <div className='item'>
            <h3></h3>
            <p></p>
          </div>
        </div>
      </div>
    </div>
  )

}

export default Residential
